version: "3"
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_TLS_CERTDIR="" 
    ports:
      - "3333:3333"
    networks:
      - jenkins
networks:
  jenkins:
    external: true
